

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb;Mode=MySQL
      username: sa
      password:
      auto-commit: true
      keepalive-time: 3000
      idle-timeout: 3000
      connection-timeout: 3000
      login-timeout: 3000

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
    default-model-expand-depth: 2
    default-models-expand-depth: 2
    operations-sorter: method
    groups-order: desc
    tags-sorter: alpha
  api-docs:
    enabled: true
    path: /szs/api-docs
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /szs/**
logging:
  level:
    web: debug
    root: debug
